config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :create] do
    resources :photos, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  
  validates :image, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy

  def is_belongs_to? user
    Post.find_by(user_id: user.id, id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:signup, keys: [:name])
    devise_parameter_sanitizer.permit(:acount_update, keys: [:name, :website, :bio])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !user_signed_in?
        redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_post, only: [:show, :destroy]

    def index
        @posts = Post.all.limit(10).includes(:photos, :user).order('created_at desc')
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
          if params[:images]
            params[:images].each do |img|
              @post.photos.create(image: params[:images][img])
            end
          end
    
          redirect_to posts_path
          flash[:notice] = "Saved ..."
        else
          flash[:alert] = "Something went wrong ..."
          redirect_to posts_path
        end
      end

    def show
        @photos = @post.photos
    end

    private
    def find_post
        @post = Post.find_by id: params[:id]
        return if @post
        flash[:danger] = "Post not found"
        redirect_to root_path
    end

    def post_params
        params.require(:post).permit :content
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    protected
  
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :authenticate_user!

    def index
    #   @users = User.search(params[:term])
      @user = User.find(params[:id])
      respond_to :js
    end
  
    def show
      @user = User.find(params[:id])
    #   set_meta_tags title: @user.name
    #   @posts = @user.posts.includes(:photos, :likes, :comments)
    #   @saved = Post.joins(:bookmarks).where("bookmarks.user_id=?", current_user.id).
    #     includes(:photos, :likes, :comments) if @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' if current_user %>

    <%= yield %>

    <%= render 'shared/footer' %>
    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr.<%= type %>('<%= value %>')
        <% end %>
      </script>
    <% end %>
    
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
  <% if post.photos.size == 1 %>
    <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top" %>
  <% else %>
    <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
      <div class="carousel-inner">
        <% post.photos.each do |photo| %>
          <% if photo == post.photos.first %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
              <%= image_tag photo.image.url(:standard), class: "card-img-top" %>
            </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <% end %>
<% end %>

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
       <img src='https://ui-avatars.com/api/?name=<%= post.user.email %>' class="no-text-decoration">
      <%# <% end %> %>
      <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
        title: post.user.name do %>
        <strong><%= post.user.name %></strong>
      <% end %>
      <% if post.is_belongs_to? current_user %>
        <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>

    <%= render "photos", {post: post} %>

    <div class="card-body">
      <div class="row actions">
        <div id="like-icon-post-<%= post.id.to_s %>">
          <%# render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>
        </div>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <div id="bookmark-icon-post-<%= post.id.to_s %>" class="ml-auto">
          <%# render "bookmark_icon", {is_bookmarked: post.is_bookmarked(current_user), post: post} %>
        </div>
      </div>
      <div id="like-text-post-<%= post.id.to_s %>">
        <%# render "like_text", {likes: post.likes} %>
      </div>
      <div>
        <span><strong><%= post.user.name %></strong></span>
        <span><%= post.content %></span>
      </div>
      <!-- load comments -->
      <div id="comment-post-<%= post.id.to_s %>">
        <%# render 'comment_list', {post: post} %>
      </div>
      <%= link_to time_ago_in_words(post.created_at).upcase + " AGO", post_path(post),
        class: "light-color post-time no-text-decoration" %>
      <hr>
      <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
        <%# render 'comment_form', {post: post} %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create Post
      </div>
      <div class="card-body">
        <%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
                <img src='https://ui-avatars.com/api/?name=<%# @post.user.email %>' class="post-author-icon">

            </div>
            <div class="col pl-0">
              <%= f.text_field :content, class: "form-control border-0",
                placeholder: "Say something about this ..." %>
            </div>
          </div>
          <div class="fallback">
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
          <div class="dz-message m-0"></div>
          <div class="dropzone-previews mb-3">
            <div class="upload-photos-icon">
              <i class="fa fa-plus fa-2x" aria-hidden="true" style="color:#dddfe2"></i>
            </div>
          </div>
          <%= f.submit "Post", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div id="posts">
      <%= render 'posts_list' %>
    </div>
  </div>
  <br>
  <%# <%= will_paginate @posts %> %>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
      <div class="align-self-center">
        <%= render "photos", {post: @post} %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex align-items-center">
        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
         <!-- <img src='https://ui-avatars.com/api/?name=<%# @user.email %>' class="post-author-icon"> -->
        <% end %>
        <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
          title: @post.user.name do %>
          <strong><%= @post.user.name %></strong>
        <% end %>
        <% if @post.is_belongs_to? current_user %>
          <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
            <i class="far fa-trash-alt" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <hr class="mb-0">
      <div class="comment-list py-2">
      <% if @post.content.present? %>
        <div>
          <span><strong><%= @post.user.name %></strong></span>
          <span><%= @post.content %></span>
        </div>
      <% end %>
        <!-- load comment -->
        <div id="comment-post-<%= @post.id.to_s %>">
          <%= render 'comment_list', post: @post %>
        </div>
      </div>
      <hr class="mt-0">

      <div class="row actions">
        <div id="like-icon-post-<%= @post.id.to_s %>">
          <%= render "like_icon", {is_liked: @is_liked, post: @post} %>
        </div>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <div id="bookmark-icon-post-<%= @post.id.to_s %>" class="ml-auto">
          <%= render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
        </div>
      </div>
      <div id="like-text-post-<%= @post.id.to_s %>">
        <%= render "like_text", {likes: @likes} %>
      </div>
      <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO</div>
      <hr>
      <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
        <%= render 'comment_form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
        <a href="" class="nav-item nav-link" href="#">BLOG</a>
        <a href="" class="nav-item nav-link" href="#">PRESS</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">JOB</a>
        <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
        <a href="" class="nav-item nav-link" href="#">TERMS</a>
        <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
        <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "Icon", root_path, class: "navbar-brand core-sprite hide-text" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search",
        remote: true do %>
        <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn",
          placeholder: "Search", autocomplete: "off" %>
        <div id="users-result"></div>
      <% end %>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <a class="nav-link core-sprite explore-icon hide-text" href="#">Explore</a>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite notification-icon hide-text" href="#">Notification</a>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link core-sprite profile-icon hide-text" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <img src='https://ui-avatars.com/api/?name=<%= @user.email %>' width='152' height='152' class="round-img">

  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.email %></p>
      <% if @user == current_user %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <a href="#" class="list-group-item list-group-item-action">Change Password</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>

  <div class="profile-tab">
    <% if @user == current_user %>
    <nav>
      <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-posts-tab" data-toggle="tab" href="#nav-posts" role="tab" aria-controls="nav-posts" aria-selected="true">POSTS</a>
        <a class="nav-item nav-link" id="nav-saved-tab" data-toggle="tab" href="#nav-saved" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</a>
      </div>
    </nav>
    <% end %>
    <div class="tab-content pb-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
        <div class="row">
          <%# render "post", {posts: @posts} %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <div class="row">
          <%# render "post", {posts: @saved} if @user == current_user %>
        </div>
      </div>
    </div> 
  </div>
</div>